const yup = require('yup')

module.exports = yup.object().shape({
  name: yup.string(),
  nominatorName: yup.string(),
  nominatorEmail: yup.string(),
  nominatorPhone: yup.string(),
  email: yup.string(),
  phone: yup.string(),
  city: yup.string(),
  facebook: yup.string(),
  linkedin: yup.string(),
  twitter: yup.string(),
  relationshipToNominator: yup.string(),
  leadership: yup.string(),
  workHistory: yup.string(),
  publicSpeaking: yup.string(),
  politicalViews: yup.string(),
  runForOffice: yup.string(),
  officeRunResults: yup.string(),
  otherInfo: yup.string(),
  districtInfo: yup.string(),
  source: yup.string(),
  submitterEmail: yup.string(),
  politicalParty: yup.string(),
  stateAbbreviation: yup.string(),
  congressionalDistrictCode: yup.string(),
  sourceTeamName: yup.string(),
  profile: yup.string(),
  otherLinks: yup.string(),
  nominatorPersonal: yup.string()
})
