const log = require('./log')

const TagMap = {
  'Alexandria Ocasio-Cortez': 'Signup: Alexandria Ocasio-Cortez',
  'available-0-5': 'Available: 0-5 Hours',
  'available-10-20': 'Available: 10-20 Hours',
  'available-20-30': 'Available: 20-30 Hours',
  'available-30': 'Available: 30+ Hours',
  'available-5-10': 'Available: 5-10 Hours',
  'CC-Nomination': 'Action: Attended CC: Nomination',
  'CC-Orientation': 'Action: Attended CC: Orientation',
  'CC-#Research': 'Action: Attended CC: Research',
  'CC-#SocialMedia': 'Action: Attended CC: Social Media',
  'CC-SOTBNC': 'Action: Attended CC: State of BNC',
  'CC-#Support': 'Action: Attended CC: Help Desk',
  'cc-tempHost': 'Action: Attended CC: Event Host',
  'coding': 'Skill: Programming',
  'corbin_editor': 'Skill: Video',
  'Data Entry': 'Skill: Data Entry',
  'e - Oakland - CA - 20160824 - Attended': 'Action: Attended Event: 2016/08/24 @ Oakland, CA ',
  'e - Olympia - WA - 20160722 - Attended': 'Action: Attended Event: 2016/07/22 @ Olympia, WA',
  'e - Omaha - NE - 20160711 - Attended': 'Action: Attended Event: 2016/07/11 @ Omaha, NE',
  'e - Orlando - FL - 20160629 - Attended': 'Action: Attended Event: 2016/06/29 @ Orlando, FL',
  'e - Overland Park - KS - 20160711 - Attended': 'Action: Attended Event: 2016/07/11 @ Overland Park, KS',
  'e - Philadelphia - PA - 20160723 - Attended': 'Action: Attended Event: 2016/07/23 @ Philadelphia, PA',
  'e - Pittsburgh - PA - 20160820 - Attended': 'Action: Attended Event: 2016/08/20 @ Pittsburgh, PA',
  'e - Providence - RI - 20160814 - Attended': 'Action: Attended Event: 2016/08/14 @ Providence, RI',
  'e - Raleigh - NC - 20160604 - Attended': 'Action: Attended Event: 2016/06/04 @ Raleigh, NC',
  'e - Rochester - NY - 20160811 - Attended': 'Action: Attended Event: 2016/08/11 @ Rochester, NY',
  'e - Sacramento - CA - 20160825 - Attended': 'Action: Attended Event: 2016/08/25 @ Sacramento, CA',
  'e - Salt Lake City - UT - 20160724 - Attended': 'Action: Attended Event: 2016/07/24 @ Salt Lake City, UT',
  'e - San Antonio - TX - 20160701 - Attended': 'Action: Attended Event: 2016/07/01 @ San Antonio, TX',
  'e - San Bernardino - CA - 20160614 - Attended': 'Action: Attended Event: 2016/06/14 @ San Bernardino, CA',
  'e - San Diego - CA - 20160826 - Attended': 'Action: Attended Event: 2016/08/26 @ San Diego, CA',
  'e - San Francisco - CA - 20160823 - Attended': 'Action: Attended Event: 2016/08/23 @ San Francisco, CA',
  'e - San Jose - CA - 20160822 - Attended': 'Action: Attended Event: 2016/08/22 @ San Jose, CA',
  'e - Santa Ana - CA - 20160719 - Attended': 'Action: Attended Event: 2016/07/19 @ Santa Ana, CA',
  'e - Santa Barbara - CA - 20160827 - Attended': 'Action: Attended Event: 2016/08/27 @ Santa Barbara, CA',
  'e - Savannah - GA - 20160711 - Attended': 'Action: Attended Event: 2016/07/11 @ Savannah, GA',
  'e - Seattle - WA - 20160720 - Attended': 'Action: Attended Event: 2016/07/20 @ Seattle, WA',
  'e - Sioux Falls - SD - 20160712 - Attended': 'Action: Attended Event: 2016/07/12 @ Sioux Falls, SD',
  'e - Spokane - WA - 20160812 - Attended': 'Action: Attended Event: 2016/08/12 @ Spokane, WA',
  'e - Stamford - CT - 20160626 - Attended': 'Action: Attended Event: 2016/06/26 @ Stamford, CT',
  'e - Syracuse - NY - 20160809 - Attended': 'Action: Attended Event: 2016/08/09 @ Syracuse, NY',
  'e - Tacoma - WA - 20160721 - Attended': 'Action: Attended Event: 2016/07/21 @ Tacoma, WA',
  'e - Tampa - FL - 20160628 - Attended': 'Action: Attended Event: 2016/06/28 @ Tampa, FL',
  'e - TX - Dallas - TX - 20160628 - Attended': 'Action: Attended Event: 2016/06/28 @ Dallas, TX',
  'Event Attended': 'Action: Attended Event',
  'Events Coordinator': 'Skill: Event Host',
  'e-volhost': 'Action: Hosted Event',
  'e - Washington DC - DC - 20160730 - Attended': 'Action: Attended Event: 2016/07/30 @ Washington, DC',
  'e - Worcester - MA - 20160806 - Attended': 'Action: Attended Event: 2016/08/06 @ Worcester, MA',
  'frequency-week-days': 'Availability: Week Days',
  'frequency-weekends': 'Availability: Weekends',
  'frequency-week-nights': 'Availability: Week Nights',
  'Graphic Design': 'Skill: Graphic Design',
  'graphics': 'Skill: Graphic Design',
  'helpdesk': 'Skill: Help Desk',
  'local-leader': 'Skill: Start Local Group',
  'muslim_ban_petition': 'Petition: Muslim Ban',
  'NB Administrator': 'Skill: Nationbuilder',
  'nominator': 'Action: Nominated Candidate',
  'nominee': 'Candidate Nominee',
  'photography': 'Skill: Photography',
  'potential-leader': 'Potential Leader',
  'printing service': 'Skill: Printing',
  'Process Engineer': 'Skill: Process Engineer',
  'programming': 'Skill: Programming',
  'q-standout': 'Potential Leader',
  'research': 'Skill: Research',
  'Ryan Stone': 'Signup: Ryan Stone',
  'Signed: Draft Cori Bush': 'Petition: Draft Cori Bush',
  'Signed: Kick out Joe Manchin': 'Petition: Kick out Joe Manchin',
  'Signed: Letter to Keith Ellison': 'Petition: Letter to Keith Ellison',
  'Signed: Medicare for All': 'Petition: Medicare for All',
  'Signed: Syrian War': 'Petition: Syrian War',
  'skill-call': 'Skill: Calling',
  'skill-calling': 'Skill: Calling',
  'skill-data entry': 'Skill: Data Entry',
  'skill-data-entry': 'Skill: Data Entry',
  'skill-event-host': 'Skill: Event Host',
  'skill-field-digital': 'Skill: Field Outreach',
  'skill-field-outreach': 'Skill: Field Outreach',
  'skill-flyer handout': 'Skill: Flyering',
  'skill-graphic-design': 'Skill: Graphic Design',
  'skill-helpdesk': 'Skill: Help Desk',
  'skill-host door knock': 'Skill: Door Knocking',
  'skill-host house party': 'Skill: Event Host',
  'skill-hr': 'Skill: HR',
  'skill-Join local group': 'Skill: Start Local Group',
  'skill-knock doors': 'Skill: Door Knocking',
  'skill-legal': 'Skill: Legal',
  'skill-manage-communities': 'Skill: Community Management',
  'skill-nationbuilder': 'Skill; Nationbuilder',
  'skill-office help': 'Skill: Office Help',
  'skill-photo': 'Skill: Photography',
  'skill-press': 'Skill: Press',
  'skill-printing': 'Skill: Printing',
  'skill-programming': 'Skill: Programming',
  'skill-research': 'Skill: Research',
  'skill-send texts': 'Skill: Texting',
  'skill-sharing': 'Skill: Social Media Sharing',
  'skill-sm-sharing': 'Skill: Social Media Sharing',
  'skill-speak to groups': 'Skill: Speaker',
  'skill-supporter-housing': 'Skill: Supporter Housing',
  'skill-travel': 'Skill: Travel Management',
  'skill-venue': 'Skill: Event Venue',
  'skill-venue-access': 'Skill: Event Venue',
  'skill-video': 'Skill: Video',
  'skill-web-design': 'Skill: Web Design',
  'skill-writing': 'Skill: Writing',
  'Social Media': 'Skill: Social Media',
  'Source: Adrienne Bell': 'Signup: Adrienne Bell',
  'Donor: Adrienne Bell': 'Donor: Adrienne Bell',
  'Source: Alexandria Ocasio-Cortez': 'Signup: Alexandria Ocasio-Cortez',
  'Donor: Alexandria Ocasio-Cortez': 'Donor: Alexandria Ocasio-Cortez',
  'Source: Anthony Clark': 'Signup: Anthony Clark',
  'Donor: Anthony Clark': 'Donor: Anthony Clark',
  'Source: Brand New Congress': 'Signup: Brand New Congress',
  'Donor: Brand New Congress': 'Donor: Brand New Congress',
  'Source: Chardo Richardson': 'Signup: Chardo Richardson',
  'Donor: Chardo Richardson': 'Donor: Chardo Richardson',
  'Source: Cori Bush': 'Signup: Cori Bush',
  'Donor: Cori Bush': 'Donor: Cori Bush',
  'Source: Danny Ellyson': 'Signup: Danny Ellyson',
  'Donor: Danny Ellyson': 'Donor: Danny Ellyson',
  'Source: Demond Drummer': 'Signup: Demond Drummer',
  'Donor: Demond Drummer': 'Donor: Demond Drummer',
  'Source: Eric Terrell': 'Signup: Eric Terrell',
  'Donor: Eric Terrell': 'Donor: Eric Terrell',
  'Source: Facebook': 'Source: Facebook',
  'Source: Hector Morales': 'Signup: Hector Morales',
  'Donor: Hector Morales': 'Donor: Hector Morales',
  'SOURCE: Incoming Call on Campaign Line': 'Source: Incoming Call',
  'Source: Incoming Call on Campaign Line': 'Source: Incoming Call',
  'Source: Justice Democrats': 'Signup: Justice Democrats',
  'Donor: Justice Democrats': 'Donor: Justice Democrats',
  'Source: Letitia Plummer': 'Signup: Letitia Plummer',
  'Donor: Letitia Plummer': 'Donor: Letitia Plummer',
  'Source: Michael Hepburn': 'Signup: Michael Hepburn',
  'Donor: Michael Hepburn': 'Donor: Michael Hepburn',
  'Source: Paula Jean': 'Signup: Paula Jean Swearengin',
  'Source: Paula Jean Swearengin': 'Signup: Paula Jean Swearengin',
  'Donor: Paula Jean Swearengin': 'Donor: Paula Jean Swearengin',
  'Source: Paul Perry': 'Signup: Paul Perry',
  'Donor: Paul Perry': 'Donor: Paul Perry',
  'Source: Richard Rice': 'Signup: Richard Rice',
  'Donor: Richard Rice': 'Donor: Richard Rice',
  'Source: Robb Ryerse': 'Signup: Robb Ryerse',
  'Donor: Robb Ryerse': 'Donor: Robb Ryerse',
  'Source: Rob Ryerse': 'Signup: Robb Ryerse',
  'Source: Ryan Stone': 'Signup: Ryan Stone',
  'Donor: Ryan Stone': 'Donor: Ryan Stone',
  'Source: Sarah Smith': 'Signup: Sarah Smith',
  'Donor: Sarah Smith': 'Donor: Sarah Smith',
  'Source: Tamarah Begay': 'Signup: Tamarah Begay',
  'Donor: Tamarah Begay': 'Donor: Tamarah Begay',
  'SOURCE: Text message received': 'Source: Incoming Text Message',
  'Source: Text message received': 'Source: Incoming Text Message',
  'Source Twitter': 'Source: Twitter',
  'Source: Twitter': 'Source: Twitter',
  'MO01-430_launch_attend': 'Action: Attended Event: 4/30/2017 @ St. Louis, MO',
  't-legal': 'Skill: Legal',
  'Tech': 'Skill: Programming',  
  'Tour_Atlanta_Attendees': 'Action: Attended Event',
  'Tour_Bridgeport_Attendees': 'Action: Attended Event',
  'Tour_Chattanooga_Attendees': 'Action: Attended Event',
  'Tour_Memphis_Attendees': 'Action: Attended Event',
  'Tour_Nashville_Attendees': 'Action: Attended Event',
  'Tour_Orlando_Attendees': 'Action: Attended Event',
  'Tour_Stamford_Attendees': 'Action: Attended Event',
  'Tour_Tampa_Attendees': 'Action: Attended Event',
  'travel': 'Skill: Travel Management',
  'Travel Coordinator': 'Skill: Travel Management',
  'venue': 'Skill: Event Venue',
  'HD-checkMEout': 'Signup: Brand New Congress',
  'hd -donation': 'Signup: Brand New Congress',
  'HD - Email blast': 'Signup: Brand New Congress',
  'HD - Local organizing': 'Signup: Brand New Congress',
  'HD(metrics) - candidate': 'Signup: Brand New Congress',
  'HD(metrics) - feedback-negative': 'Signup: Brand New Congress',
  'HD(metrics) - feedback-positive': 'Signup: Brand New Congress',
  'HD(metrics) - involvement': 'Signup: Brand New Congress',
  'HD(metrics) - policy': 'Signup: Brand New Congress',
  'HD(metrics) - question': 'Signup: Brand New Congress',
  'HD(metrics) - reroute': 'Signup: Brand New Congress',
  'HD(metrics) - technical issue': 'Signup: Brand New Congress',
  'HD - MyAwesomeProject': 'Signup: Brand New Congress',
  'hd-myidea': 'Signup: Brand New Congress',
  'HD - Rant': 'Signup: Brand New Congress',
  'HD - Skills': 'Signup: Brand New Congress',
  'HD - Spam': 'Signup: Brand New Congress',
  'HD - STANDOUT! volunteer': 'Signup: Brand New Congress',
  'HD - VIP': 'Signup: Brand New Congress',
  'HD - Wiki/District info': 'Signup: Brand New Congress',
  'mo01-17_05_06_cinco': 'Action: Attended Event: 2017/05/06 @ St. Louis, MO',
  'mo01-17_05_07_beertree': 'Action: Attended Event: 2017/05/07 @ St. Louis, MO',
  'mo01-17_05_13_78jobfair': 'Action: Attended Event: 2017/05/13 @ St. Louis, MO',
  'mo01-5-3_riffraff_signup': 'Action: Attended Event: 2017/05/03 @ St. Louis, MO',
  'networker': 'Signup: Brand New Congress',
  'new-test': 'Signup: Brand New Congress',
  'NLL': 'Signup: Brand New Congress',
  'Office-suggestion': 'Signup: Brand New Congress',
  'Omaha': 'Signup: Brand New Congress',
  'Orient': 'Signup: Brand New Congress',
  'pa': 'Signup: Brand New Congress',
  'Path:Events:Step:Attended': 'Signup: Brand New Congress',
  'Path:Events:Step:Registered': 'Signup: Brand New Congress',
  'Path:Team-Support:Step:Trial': 'Signup: Brand New Congress',
  'potentialdonor': 'Signup: Brand New Congress',
  'potentialdonor-recurring': 'Signup: Brand New Congress',
  'potential-partner': 'Signup: Brand New Congress',
  'Procurement Specialist': 'Signup: Brand New Congress',
  'programming_ helpdesk': 'Skill: Programming',
  'Research_book': 'Skill: Research',
  'resume': 'Signup: Brand New Congress',
  'RFSE': 'Signup: Brand New Congress',
  's-BernieBuilders': 'Signup: Brand New Congress',
  'Signup': 'Signup: Brand New Congress',
  'signup-nb': 'Signup: Brand New Congress',
  'skill-donate monthly': 'Signup: Brand New Congress',
  'Source: Chardo Richardon': 'Signup: Chardo Richardson',
  'special skills': 'Signup: Brand New Congress',
  'still-host phone/text bank': 'Skill: Event Host',
  's-TNforBernie': 'Signup: Brand New Congress',
  'suggestion-partnership': 'Signup: Brand New Congress',
  'suggestion - platform': 'Signup: Brand New Congress',
  's-WAforBernie': 'Signup: Brand New Congress',
  'international-mexico': 'Signup: Brand New Congress',
  'Invite-Liam': 'Signup: Brand New Congress',
  'local-events': 'Signup: Brand New Congress',
  'local organizer': 'Signup: Brand New Congress',
  'l - Spanish': 'Signup: Brand New Congress',
  'NC-temp': 'Signup: Brand New Congress',
  'negative': 'Signup: Brand New Congress',
  'news': 'Signup: Brand New Congress',
  'medicare': 'Petition: Medicare for All',
  'ID: MO01 - 1 - Strong Support': 'ID: MO01 - 1 - Strong Support',
  'ID: MO01 - 2 - Lean Support': 'ID: MO01 - 2 - Lean Support',
  'ID: MO01 - 3 - Undecided': 'ID: MO01 - 3 - Undecided',
  'ID: MO01 - 4 - Lean Opponent': 'ID: MO01 - 4 - Lean Opponent',
  'ID: MO01 - 5 - Strong Opponent': 'ID: MO01 - 5 - Strong Opponent',
  'ID: MO01 - 8 - Not Voting': 'ID: MO01 - 8 - Not Voting',
  'ID: MO01 - Have ID': 'ID: MO01 - Have ID',
  'MO01_bz_contact_only': 'MO01_bz_contact_only',
  'MO01-No_to_rally': 'MO01: No to rally',
  'MO01-Yes_to_rally': 'MO01-Yes_to_rally',
  'mo01-Brendans_friends': 'mo01-Brendans_friends',
  'movoters:MO-Federal-1 - 04/20/2017 14:15:34:439': 'movoters:MO-Federal-1 - 04/20/2017 14:15:34:439',
  'NEIGHBORHOOD: 10th Ward': 'NEIGHBORHOOD: 10th Ward',
  'NEIGHBORHOOD: 27th Ward': 'NEIGHBORHOOD: 27th Ward',
  'NEIGHBORHOOD: 3rd Ward': 'NEIGHBORHOOD: 3rd Ward',
  'NEIGHBORHOOD: Afton': 'NEIGHBORHOOD: Afton',
  'NEIGHBORHOOD: Arnold': 'NEIGHBORHOOD: Arnold',
  'NEIGHBORHOOD: Benton Park West': 'NEIGHBORHOOD: Benton Park West',
  'NEIGHBORHOOD: Bevo': 'NEIGHBORHOOD: Bevo',
  'NEIGHBORHOOD: Carondelet': 'NEIGHBORHOOD: Carondelet',
  'NEIGHBORHOOD: Central West End': 'NEIGHBORHOOD: Central West End',
  'NEIGHBORHOOD: Cherokee': 'NEIGHBORHOOD: Cherokee',
  'NEIGHBORHOOD: Columbia': 'NEIGHBORHOOD: Columbia',
  'NEIGHBORHOOD: DeMun/Clayton near Skinker': 'NEIGHBORHOOD: DeMun/Clayton near Skinker',
  'NEIGHBORHOOD: Dogtown': 'NEIGHBORHOOD: Dogtown',
  'NEIGHBORHOOD: Downtown': 'NEIGHBORHOOD: Downtown',
  'NEIGHBORHOOD: Ferguson': 'NEIGHBORHOOD: Ferguson',
  'NEIGHBORHOOD: Florissant': 'NEIGHBORHOOD: Florissant',
  'NEIGHBORHOOD: Forest Park SE': 'NEIGHBORHOOD: Forest Park SE',
  'NEIGHBORHOOD: Glendale': 'NEIGHBORHOOD: Glendale',
  'NEIGHBORHOOD: Gravois Park': 'NEIGHBORHOOD: Gravois Park',
  'NEIGHBORHOOD: Independence': 'NEIGHBORHOOD: Independence',
  'NEIGHBORHOOD: Jennings': 'NEIGHBORHOOD: Jennings',
  'NEIGHBORHOOD: Kirkwood': 'NEIGHBORHOOD: Kirkwood',
  'NEIGHBORHOOD: Lebanon': 'NEIGHBORHOOD: Lebanon',
  'NEIGHBORHOOD: Mackenzie Hills': 'NEIGHBORHOOD: Mackenzie Hills',
  'NEIGHBORHOOD: Maplewood': 'NEIGHBORHOOD: Maplewood',
  'NEIGHBORHOOD: Marine Villa': 'NEIGHBORHOOD: Marine Villa',
  'NEIGHBORHOOD: Maryland Heights': 'NEIGHBORHOOD: Maryland Heights',
  'NEIGHBORHOOD: Midtown': 'NEIGHBORHOOD: Midtown',
  'NEIGHBORHOOD: Old North': 'NEIGHBORHOOD: Old North',
  'NEIGHBORHOOD: Overland': 'NEIGHBORHOOD: Overland',
  'NEIGHBORHOOD: Richmond Heights': 'NEIGHBORHOOD: Richmond Heights',
  'NEIGHBORHOOD: Rock Hill': 'NEIGHBORHOOD: Rock Hill',
  'NEIGHBORHOOD: Rolla': 'NEIGHBORHOOD: Rolla',
  'NEIGHBORHOOD: Shaw': 'NEIGHBORHOOD: Shaw',
  'NEIGHBORHOOD: Southwest Gardens': 'NEIGHBORHOOD: Southwest Gardens',
  'NEIGHBORHOOD: Springfield': 'NEIGHBORHOOD: Springfield',
  'NEIGHBORHOOD: St_ Charles': 'NEIGHBORHOOD: St_ Charles',
  'NEIGHBORHOOD: St_ Louis Place': 'NEIGHBORHOOD: St_ Louis Place',
  'NEIGHBORHOOD: The Hill': 'NEIGHBORHOOD: The Hill',
  'NEIGHBORHOOD: Tower Grove East': 'NEIGHBORHOOD: Tower Grove East',
  'NEIGHBORHOOD: Tower Grove South': 'NEIGHBORHOOD: Tower Grove South',
  'NEIGHBORHOOD: U City': 'NEIGHBORHOOD: U City',
  'NEIGHBORHOOD: Valley Park': 'NEIGHBORHOOD: Valley Park',
  'NEIGHBORHOOD: Walnut Park East': 'NEIGHBORHOOD: Walnut Park East',
  'NEIGHBORHOOD: West County': 'NEIGHBORHOOD: West County',
  'Alabama_Press_List': null,
  'Alaska_Press_List': null,
  'Arkansas_Press_List': null,
  'California_Press_List': null,
  'Colorado_Press_List': null,
  'Community Newspaper': null,
  'Connecticut_Press_List': null,
  'Daily Newspaper': null,
  'Daily Newspaper Bureau': null,
  'Delaware_Press_List': null,
  'Florida_Press_List': null,
  'Georgia_Press_List': null,
  'Magazine': null,
  'Magazine Bureau': null,
  'National_Press_List': null, 
  'orlando_press': null,
  'Paula_Swearengin_national': null,
  'press': null,
  'press-hotlist': null,
  'press-hotlist+tyt': null,
  'stl_press': null,
  'Supporter': null,
  'Texas_Press_List': null,
  'text_opt_out': null
}

function convertTags(tags) {
  const reverseTagMap = {}
  Object.keys(TagMap).forEach((tag) => {
    const reverseTag = TagMap[tag]
    if (reverseTag !== null) {
      reverseTagMap[reverseTag] = tag
    }
  })
  let newTags = []
  if (tags.length === 1 && tags[0] === 'Supporter') {
    newTags = ['Source: Brand New Congress']
  } else {
    newTags = tags.map((tag) => {
      if (TagMap.hasOwnProperty(tag)) {
        return TagMap[tag]
      } else if (reverseTagMap.hasOwnProperty(tag)) {
        return tag
      } else {
        log.error(`Cannot find tag anywhere ${tag}`)
        return null
      }
    })
  }
  newTags = newTags.filter((ele) => ele !== null)
  newTags = newTags.filter((ele, pos) => newTags.indexOf(ele) === pos)
  return newTags
}

module.exports = {
  convertTags
}
