module.exports = [
  ['justicedemocrats.com', 'Justice Democrats'],
  ['votecoribush.com', 'Cori Bush'],
  ['paulajean2018.com', 'Paula Jean'],
  ['coribush', 'Cori Bush'],
  ['paulajean', 'Paula Jean Swearengin'],
  ['sarahsmith', 'Sarah Smith'],
  ['letitiaplummer', 'Letitia Plummer'],
  ['anthonyclark', 'Anthony Clark'],
  ['richardrice', 'Richard Rice'],
  ['demonddrummer', 'Demond Drummer'],
  ['robbryerse', 'Robb Ryerse'],
  ['michaelhephburn', 'Michael Hephburn'],
  ['chardorichardson', 'Chardo Richardon'],
  ['dannyellyson', 'Danny Ellyson'],
  ['ericterrell', 'Eric Terrell'],
  ['adrienneebell', 'Adriene Bell'],
  ['alexandriaocasio', 'Alexandra Ocasio'],
  ['brandnewcongress', 'General Brand New Congress']
]
